spring:
  mongodb.embedded.version: "3.6.0"
  data.mongodb.database: library
  main.allow-circular-references: true
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: library
#      username: peyba
#      password: Perec6
#
#  main:
#    allow-circular-references: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework08.mongock.changelog
  mongo-db:
    write-concern:
      journal: false